language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"

install:
  # Install a recent build of pypy3.
  # https://github.com/frol/flask-restplus-server-example/blob/master/.travis.yml
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy3" ]; then
        PYPY3_VERSION="pypy3.3-5.5-alpha"
        PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "$PYPY3_VERSION"
        virtualenv --version
        virtualenv --python="$PYENV_ROOT/versions/$PYPY3_VERSION/bin/python" --no-setuptools --no-pip "$HOME/virtualenvs/$PYPY3_VERSION"
        source "$HOME/virtualenvs/$PYPY3_VERSION/bin/activate"
      fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ]; then pip3 install codecov; fi
script:
  - python3 -c "import unicodedata; print(unicodedata.unidata_version)"
  - python3 -m unittest discover
  - python3 -m doctest README.rst
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ]; then coverage run --source precis_i18n -m unittest test/test_precis.py test/test_codepointset.py test/test_codec.py test/test_factory.py; fi

after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ]; then codecov; fi

